#!/bin/bash

set -e

# modify server.cnf
sed -i "/\[mysqld\]/a collation-server = utf8_unicode_ci\ninit-connect='SET NAMES utf8'\ncharacter-set-server = utf8" /etc/my.cnf.d/server.cnf
# modify mysql-clients.cnf
sed -i "/\[mysql\]/a default-character-set=utf8" /etc/my.cnf.d/mysql-clients.cnf
echo "===> Mariadb config completed..."

# supervisor for mariadb
cat > /etc/supervisor.conf.d/mysql.conf <<EOF
[program:mysql]
directory=/
command=/usr/bin/mysqld_safe
user=mysql
autostart=true
autorestart=true
stdout_logfile=/var/log/supervisor/%(program_name)s.log
stderr_logfile=/var/log/supervisor/%(program_name)s.log
EOF
touch firstrun
echo "===> Mariadb completed..."