#!/bin/bash

set -e

#
# When Startup Container script
#

runStart() {
	if [[ -e /firstrun ]]; then
		# config mariadb
		source /scripts/firstrun_maria
        firstrun_maria
    	rm /firstrun
    else
		# Cleanup previous mariadb sockets
        if [[ -e ${DATA_DIR}/mysql.sock ]]; then
            rm -f ${DATA_DIR}/mysql.sock
        fi
    fi
	exec /usr/bin/supervisord -n -c /etc/supervisord.conf
}

runStart