#!/bin/bash

set -e

# Create html directory
mkdir -p /app
echo "===> ${HTML_DIR} directroy created..."

# Cover Nginx default config files
cp -f /setup/nginx/default.conf /etc/nginx/conf.d/default.conf
echo "===> nginx default.conf copy completed..."
cp -f /setup/nginx/nginx.conf /etc/nginx/nginx.conf
echo "===> Nginx config completed...."

# Nginx default information file move to ${HTML_DIR}
mv /usr/share/nginx/html/* ${HTML_DIR}
echo "<?php phpinfo(); ?>" > /app/info.php

# Grant nginx for html directory 
chown nginx:nginx -R ${HTML_DIR}
chown root.nginx -R /var/lib/php/session

# Config php-fpm
cp /setup/php/www.conf /etc/php-fpm.d/www.conf
sed -i 's/;cgi.fix_pathinfo=1/cgi.fix_pathinfo=0/' /etc/php.ini

# Nginx supervisor config
cat > /etc/supervisor.conf.d/nginx.conf <<EOF
[program:nginx]
directory=/
command=/usr/sbin/nginx -c /etc/nginx/nginx.conf
user=root
autostart=true
autorestart=true
stdout_logfile=/var/log/supervisor/%(program_name)s.log
stderr_logfile=/var/log/supervisor/%(program_name)s.log
EOF
echo "===> Nginx completed..."

# PHP-FPM supervisor config
cat > /etc/supervisor.conf.d/php-fpm.conf <<EOF
[program:php-fpm]
directory=/
command=/usr/sbin/php-fpm
user=root
autostart=true
autorestart=true
stdout_logfile=/var/log/supervisor/%(program_name)s.log
stderr_logfile=/var/log/supervisor/%(program_name)s.log
EOF
echo "===> PHP-FPM completed..."