#
# MAINTAINER        Carson,C.J.Zeong <zcy@nicescale.com>
# DOCKER-VERSION    1.6.2
#
# Dockerizing Wordpress: Dockerfile for building Wordpress images
#
FROM       csphere/demoweb:0.1
MAINTAINER Carson,C.J.Zeong <zcy@nicescale.com>