#!/bin/bash

set -e

# Setting System TimeZone
ln -sf /usr/share/zoneinfo/Asia/Shanghai /etc/localtime

# Fix sudo need tty bug
sed -i "s/Defaults    requiretty/#Defaults    requiretty/" /etc/sudoers

echo "===> TimeZone and sudoers settings fixed..."

# Create the Supervisor config directory
mkdir -p /etc/supervisor.conf.d
mkdir -p /var/log/supervisor
echo "===> Directory created..."

#
# Copy supervisor.conf
#
cp /setup/supervisord.conf /etc/supervisord.conf
echo "===> supervisord setup completed..."